# Site settings
title: jetzatle
header-img:
email: email.kraus@gmail.com
description: "So many ideas, so little time"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jetzatle
github_username:  m-kraus
facebook_username:

# Build settings
#markdown: kramdown
#kramdown:
#  input: GFM
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
